### ISSUE TITLE
可否详细讲一下 更改方块的RenderType

### ISSUE THREAD

**Issue by 2651084156** [vvvbbbcz/ModderGuide#1]
代码我是这样子写的
![图片](https://user-images.githubusercontent.com/69307837/166147608-1076cddd-855f-44e5-acb4-79a9f675559a.png)
应该没有问题？
但是这还是黑的emmm
![图片](https://user-images.githubusercontent.com/69307837/166147472-a6dcca7a-f16a-48c9-a516-759633b87407.png)
或者给点完整的例子emmmm

**Comment by vvvbbbcz** [comment]
doClientStuff不是这样用的。。
你要在主类添加这个方法的监听
